createReservoir.base <-
function(type,name,label,priority,downstream,netEvaporation,
         seepageFraction,seepageCode,geometry,plant,
         penstock,initialStorage)
{
   reservoir<-list(type=type,
                   name=name,
                   label=label,
                   priority=priority,
                   downstream=downstream,
                   netEvaporation=netEvaporation,
                   seepageFraction=seepageFraction,
                   seepageCode=seepageCode,
                   geometry=geometry,
                   plant=plant,
                   penstock=penstock,
                   initialStorage=initialStorage)
   return(reservoir)
}